# Generated by Django 2.2.5 on 2021-07-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='list',
        ),
    ]
